### ISSUE TITLE
Error 204 on myket [Resolved]

### ISSUE THREAD

**Issue by cspannery** [nivadcloud/InAppBillingAndroidSample#3]
Hi , i aded nivad api into my app and try to buy a product and every time i try the 204 errorCode is thrown 

Log's :
`07-24 15:29:43.144 22264-22264/  D/nivad: resultCode = -1, responseCode = 0
07-24 15:29:43.145 22264-522/  I/nivad: Checking purchase. Attempt 1
07-24 15:29:43.145 22264-522/  I/Nivad API: Checking purchase validity
07-24 15:29:43.145 22264-522/  D/API: Making a POST request to https://api.nivad.io/v1/billing/check/purchase
07-24 15:29:43.341 22264-522/  W/System.err: javax.net.ssl.SSLHandshakeException: Chain validation failed
07-24 15:29:43.341 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
07-24 15:29:43.341 22264-522/  W/System.err:     at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:406)
07-24 15:29:43.341 22264-522/  W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
07-24 15:29:43.341 22264-522/  W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
07-24 15:29:43.341 22264-522/  W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
07-24 15:29:43.341 22264-522/  W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
07-24 15:29:43.341 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
07-24 15:29:43.342 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
07-24 15:29:43.342 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
07-24 15:29:43.342 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.342 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.342 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.342 22264-522/  W/System.err:     at io.nivad.iab.BillingProcessor.a(Unknown Source)
07-24 15:29:43.342 22264-522/  W/System.err:     at io.nivad.iab.BillingProcessor.a(Unknown Source)
07-24 15:29:43.342 22264-522/  W/System.err:     at io.nivad.iab.i.a(Unknown Source)
07-24 15:29:43.342 22264-522/  W/System.err:     at io.nivad.iab.i.doInBackground(Unknown Source)
07-24 15:29:43.342 22264-522/  W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-24 15:29:43.342 22264-522/  W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-24 15:29:43.342 22264-522/  W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-24 15:29:43.342 22264-522/  W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-24 15:29:43.342 22264-522/  W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-24 15:29:43.342 22264-522/  W/System.err:     at java.lang.Thread.run(Thread.java:761)
07-24 15:29:43.342 22264-522/  W/System.err: Caused by: java.security.cert.CertificateException: Chain validation failed
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:610)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:464)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
07-24 15:29:43.342 22264-522/  W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
07-24 15:29:43.342 22264-522/  W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
07-24 15:29:43.342 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
07-24 15:29:43.342 22264-522/  W/System.err: 	... 21 more
07-24 15:29:43.342 22264-522/  W/System.err: Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
07-24 15:29:43.342 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:127)
07-24 15:29:43.342 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:215)
07-24 15:29:43.342 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:143)
07-24 15:29:43.342 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
07-24 15:29:43.343 22264-522/  W/System.err:     at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
07-24 15:29:43.343 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:606)
07-24 15:29:43.343 22264-522/  W/System.err: 	... 33 more
07-24 15:29:43.343 22264-522/  W/System.err: Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Sun Jul 23 13:10:00 GMT+00:00 2017 (compared to Mon Jul 24 15:29:43 GMT+00:00 2017)
07-24 15:29:43.343 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:234)
07-24 15:29:43.343 22264-522/  W/System.err:     at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
07-24 15:29:43.343 22264-522/  W/System.err:     at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
07-24 15:29:43.343 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:119)
07-24 15:29:43.343 22264-522/  W/System.err: 	... 38 more
07-24 15:29:43.343 22264-522/  D/nivad: Retry checking purchase status
07-24 15:29:43.343 22264-522/  I/nivad: Checking purchase. Attempt 2
07-24 15:29:43.343 22264-522/  I/Nivad API: Checking purchase validity
07-24 15:29:43.343 22264-522/  D/API: Making a POST request to https://api.nivad.io/v1/billing/check/purchase
07-24 15:29:43.657 22264-522/  W/System.err: javax.net.ssl.SSLHandshakeException: Chain validation failed
07-24 15:29:43.657 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
07-24 15:29:43.657 22264-522/  W/System.err:     at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:406)
07-24 15:29:43.657 22264-522/  W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
07-24 15:29:43.657 22264-522/  W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
07-24 15:29:43.657 22264-522/  W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
07-24 15:29:43.657 22264-522/  W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
07-24 15:29:43.657 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
07-24 15:29:43.657 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
07-24 15:29:43.657 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
07-24 15:29:43.657 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.657 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.657 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.657 22264-522/  W/System.err:     at io.nivad.iab.BillingProcessor.a(Unknown Source)
07-24 15:29:43.657 22264-522/  W/System.err:     at io.nivad.iab.BillingProcessor.a(Unknown Source)
07-24 15:29:43.657 22264-522/  W/System.err:     at io.nivad.iab.i.a(Unknown Source)
07-24 15:29:43.657 22264-522/  W/System.err:     at io.nivad.iab.i.doInBackground(Unknown Source)
07-24 15:29:43.657 22264-522/  W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-24 15:29:43.657 22264-522/  W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-24 15:29:43.657 22264-522/  W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-24 15:29:43.657 22264-522/  W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-24 15:29:43.657 22264-522/  W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-24 15:29:43.657 22264-522/  W/System.err:     at java.lang.Thread.run(Thread.java:761)
07-24 15:29:43.657 22264-522/  W/System.err: Caused by: java.security.cert.CertificateException: Chain validation failed
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:610)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:464)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
07-24 15:29:43.658 22264-522/  W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
07-24 15:29:43.658 22264-522/  W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
07-24 15:29:43.658 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
07-24 15:29:43.658 22264-522/  W/System.err: 	... 21 more
07-24 15:29:43.658 22264-522/  W/System.err: Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
07-24 15:29:43.659 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:127)
07-24 15:29:43.659 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:215)
07-24 15:29:43.659 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:143)
07-24 15:29:43.659 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
07-24 15:29:43.659 22264-522/  W/System.err:     at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
07-24 15:29:43.659 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:606)
07-24 15:29:43.659 22264-522/  W/System.err: 	... 33 more
07-24 15:29:43.660 22264-522/  W/System.err: Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Sun Jul 23 13:10:00 GMT+00:00 2017 (compared to Mon Jul 24 15:29:43 GMT+00:00 2017)
07-24 15:29:43.660 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:234)
07-24 15:29:43.660 22264-522/  W/System.err:     at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
07-24 15:29:43.660 22264-522/  W/System.err:     at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
07-24 15:29:43.660 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:119)
07-24 15:29:43.660 22264-522/  W/System.err: 	... 38 more
07-24 15:29:43.661 22264-522/  D/nivad: Retry checking purchase status
07-24 15:29:43.661 22264-522/  I/nivad: Checking purchase. Attempt 3
07-24 15:29:43.661 22264-522/  I/Nivad API: Checking purchase validity
07-24 15:29:43.662 22264-522/  D/API: Making a POST request to https://api.nivad.io/v1/billing/check/purchase
07-24 15:29:43.811 22264-522/  W/System.err: javax.net.ssl.SSLHandshakeException: Chain validation failed
07-24 15:29:43.811 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
07-24 15:29:43.811 22264-522/  W/System.err:     at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:406)
07-24 15:29:43.811 22264-522/  W/System.err:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
07-24 15:29:43.811 22264-522/  W/System.err:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
07-24 15:29:43.811 22264-522/  W/System.err:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
07-24 15:29:43.811 22264-522/  W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
07-24 15:29:43.811 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
07-24 15:29:43.811 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
07-24 15:29:43.811 22264-522/  W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
07-24 15:29:43.811 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.812 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.812 22264-522/  W/System.err:     at io.nivad.iab.a.a(Unknown Source)
07-24 15:29:43.812 22264-522/  W/System.err:     at io.nivad.iab.BillingProcessor.a(Unknown Source)
07-24 15:29:43.812 22264-522/  W/System.err:     at io.nivad.iab.BillingProcessor.a(Unknown Source)
07-24 15:29:43.812 22264-522/  W/System.err:     at io.nivad.iab.i.a(Unknown Source)
07-24 15:29:43.812 22264-522/  W/System.err:     at io.nivad.iab.i.doInBackground(Unknown Source)
07-24 15:29:43.812 22264-522/  W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-24 15:29:43.812 22264-522/  W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-24 15:29:43.812 22264-522/  W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-24 15:29:43.812 22264-522/  W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-24 15:29:43.812 22264-522/  W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-24 15:29:43.812 22264-522/  W/System.err:     at java.lang.Thread.run(Thread.java:761)
07-24 15:29:43.812 22264-522/  W/System.err: Caused by: java.security.cert.CertificateException: Chain validation failed
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:610)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:444)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:464)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
07-24 15:29:43.812 22264-522/  W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
07-24 15:29:43.812 22264-522/  W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
07-24 15:29:43.812 22264-522/  W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
07-24 15:29:43.813 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
07-24 15:29:43.813 22264-522/  W/System.err: 	... 21 more
07-24 15:29:43.813 22264-522/  W/System.err: Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
07-24 15:29:43.813 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:127)
07-24 15:29:43.813 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:215)
07-24 15:29:43.813 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:143)
07-24 15:29:43.813 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
07-24 15:29:43.813 22264-522/  W/System.err:     at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
07-24 15:29:43.813 22264-522/  W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:606)
07-24 15:29:43.813 22264-522/  W/System.err: 	... 33 more
07-24 15:29:43.813 22264-522/  W/System.err: Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Sun Jul 23 13:10:00 GMT+00:00 2017 (compared to Mon Jul 24 15:29:43 GMT+00:00 2017)
07-24 15:29:43.813 22264-522/  W/System.err:     at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:234)
07-24 15:29:43.813 22264-522/  W/System.err:     at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:194)
07-24 15:29:43.813 22264-522/  W/System.err:     at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
07-24 15:29:43.813 22264-522/  W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:119)
07-24 15:29:43.813 22264-522/  W/System.err: 	... 38 more
07-24 15:29:43.813 22264-522/  D/nivad: Retry checking purchase status
07-24 15:29:43.813 22264-522/  I/nivad: Attempted 3 times and failed to validate purchase. Assuming the purchase is invalid
`

**Comment by cspannery** [comment]
مرتب خطای 204 میده ، خطای اتصال به نیواد

**Comment by cspannery** [comment]
مشکل حل شد !  مشکل از این بود که من میخواستم فقط از مایکت استفاده کنم لذا بازار رو وصل نکرده بودم به خاطر عدم وصل بودن بازار خطا میداد که بعد از وصل بازار مشکل حل شد !

Problem Resolved  !   
The Error Was Occurred Because I Didn't Connect Nivad To Bazaar Market .
And After I Add Bazaar to Nivad The Issue Resolved !
